apiVersion: v1
kind: Pod
metadata:
  name: haproxy
  labels:
    app: proxy 
spec:
  containers:
    - name: haproxy
      image: gcr.io/johopets/haproxy:1.5
      imagePullPolicy: Always
      ports:
        - containerPort: 80
