apiVersion: v1
kind: Pod
metadata:
  name: nginx 
  labels:
    app: proxy 
spec:
  containers:
    - name: nginx 
      image: gcr.io/johopets/nginx-test
      imagePullPolicy: Always
      ports:
        - containerPort: 80
