apiVersion: v1
kind: Service
metadata: 
  name: couchdb
  labels: 
    name: couchdb
spec: 
  ports:
    # the port that this service should serve on
    - port: 5984 
      targetPort: 5984
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: couchdb 
